### ISSUE TITLE
sumSpectra -> summary

### ISSUE THREAD

**Issue by zeehio** [bryanhanson/ChemoSpecUtils#1]
R has a summary generic for its objects. You can do:

```r
data(iris)
summary(iris)
summary(1:1000)
```

What if instead of defining `sumSpectra` (which could be though as "sum the Spectra") you use directly the summary generic?

I can provide a pull request if you want. Basically instead of defining `sumSpectra.Spectra` you would define `summary.Spectra`

**Comment by bryanhanson** [comment]
Since `Spectra` objects are lists, `R` would default to its list summary method.  If you look at `sumSpectra.Spectra` you'll see that it does a lot more work that `R` would give via default.  If you need something simpler you might consider `str(Spectra)`.

**Comment by zeehio** [comment]
If the class of Spectra objects is `Spectra` you can define `summary.Spectra` and that method will be used when calling `summary()`, instead of the default `summary.list`. But do as you prefer :-)

**Comment by bryanhanson** [comment]
I see what you are getting at: `summary` instead of `sumSpectra`.  I will think about that for the version after next.  I would probably map it so that either works, so as users who are accustomed to `sumSpectra` dont' have to change their habits.  Thanks for the suggestion.

**Comment by bryanhanson** [comment]
`sumSpectra.Spectra` and `sumSpectra.Spectra2D` are implemented in https://github.com/bryanhanson/ChemoSpecUtils/commit/7927355763dac08a0a4ecca86526bbed423a4302 In a future release these could be renamed as suggested in this thread, but for now, we'll leave as is.
